# Config file

paths:
  metrics: './results/logs'
  figures: './results/figures'
  models: './results/models'

model:
  type: ['pspnet', 'deeplabv3_plus', 'unet']
  backbone: resnet101
  pretrained: imagenet
  classes: 3
  activation: null

training:
  epochs: 100
  loss_function:
    type: focal_loss
  metrics:
    - foreground_acc
    - DiceMulti
    - JaccardCoeffMulti

data:
  path_to_dataset: './data/processed/train'
  path_test_dataset: './data/processed/val'
  batch_size: 32
  augmentation:
    resize: [256, 256]
    shadow_transform:
      num_shadows: 3
      min_opacity: 0.5
      max_opacity: 0.75
    normalize: imagenet_stats
    aug_transforms:
      mult: 2
      do_flip: true
      flip_vert: true
      max_rotate: 90.0
      min_zoom: 0.8
      max_zoom: 3.0
      max_lighting: 0.2
      max_warp: 0.2
      p_affine: 0.75
      p_lighting: 0.75
  mapping_class_color:
    - color: [107, 142, 35]   # No se cual era
      class: 0 
    - color: [102, 102, 156]  # No se cual era
      class: 0
    - color: [128, 64, 128]   # Road
      class: 1
    - color: [0, 0, 142]      # Car
      class: 2
    - color: [0, 0, 0]        # Background
      class: 0